version: '3'

services:

  forum-database:
    image: "postgres"
    container_name: forum-database
    volumes:
      - forum-data:/var/lib/postgresql/data
    ports:
      - 5400:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  forum-app:
    build: .
    container_name: forum-app
    environment:
      - DB_HOST=forum-database
    ports:
      - 8008:8008
    depends_on:
      forum-database:
        condition: service_healthy
    links:
      - forum-database

volumes:
  forum-data:
